apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-pv
  labels:
    app: {{ .Values.name }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  capacity:
    storage: {{ .Values.storageCapacity }}
  accessModes:
    - {{ .Values.accessMode }}
  hostPath:
    path: {{ .Values.volumes.dataVolume.mountPath }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-pvc
  labels:
    app: {{ .Values.name }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - {{ .Values.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storageCapacity }}
