name: "s3proxy"

replicas: 1

image: "andrewgaul/s3proxy"
containerPort: 80

envs:
  s3proxyAuthtorization:
    name: "S3PROXY_AUTHORIZATION"
    value: "none"

volumes:
  dataVolume:
    name: "data-volume"
    mountPath: "/data"
    hostPath: ""

serviceType: "NodePort"

exposedPort: 80
