server:
  port: 8082

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/d2
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin

amazon:
  s3:
    image-bucket: d2-images
    key-prefix: photos
