apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.serviceType }}
  ports:
    - protocol: {{ .Values.servicePorts.tcp.protocol }}
      port: {{ .Values.servicePorts.tcp.port }}
