server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      schema: image-service

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"